/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.info;

/**
 *
 * @author snehaswaroop
 */




public class CreateLicense extends javax.swing.JPanel {

    /**
     * Creates new form CreateLicense
     */
    
    String Path = null;
    
    
    info Info;
    
    public CreateLicense(info Info) {
        initComponents();
        this.Info = Info;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateLicInfo = new javax.swing.JLabel();
        lblCreateLicNum = new javax.swing.JLabel();
        txtLicNum = new javax.swing.JTextField();
        lblCreateDOI = new javax.swing.JLabel();
        txtDOI = new javax.swing.JTextField();
        lblcreateDOE = new javax.swing.JLabel();
        txtDOE = new javax.swing.JTextField();
        lblBloodType = new javax.swing.JLabel();
        txtBloodType = new javax.swing.JTextField();
        btnSavePic = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtUp = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));

        lblCreateLicInfo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCreateLicInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateLicInfo.setText("Create License Information");

        lblCreateLicNum.setText("License Number");

        lblCreateDOI.setText("Date Of Issue");

        lblcreateDOE.setText("Date Of Expiration");

        lblBloodType.setText("Blood Type");

        btnSavePic.setText("Upload");
        btnSavePic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePicActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtUp.setText("UPLOAD PICTURE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCreateLicInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBloodType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblcreateDOE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCreateDOI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCreateLicNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUp, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtLicNum)
                        .addComponent(txtDOI)
                        .addComponent(txtDOE)
                        .addComponent(txtBloodType, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                    .addComponent(btnSavePic, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(lblCreateLicInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateLicNum)
                    .addComponent(txtLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateDOI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDOE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcreateDOE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBloodType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSavePic)
                    .addComponent(txtUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        Info.setLicense_Number(txtLicNum.getText());
        Info.setDate_Of_Issue(txtDOI.getText());
        Info.setDate_Of_Expiration(txtDOE.getText());
        Info.setBlood_Type(txtBloodType.getText());
        Info.setPic(txtUp.getText());
        
        JOptionPane.showMessageDialog(this, "License Information Saved");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSavePicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePicActionPerformed
        // TODO add your handling code here:
        
        JFileChooser file = new JFileChooser();
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            txtUp.setText(path);
            Info.setPic(txtUp.getText());
            //String image = txt_filename.getText();
            //image = image.replace("\\","\\\\");
            
            
         
            
        }
        
    }//GEN-LAST:event_btnSavePicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSavePic;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblCreateDOI;
    private javax.swing.JLabel lblCreateLicInfo;
    private javax.swing.JLabel lblCreateLicNum;
    private javax.swing.JLabel lblcreateDOE;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtDOE;
    private javax.swing.JTextField txtDOI;
    private javax.swing.JTextField txtLicNum;
    private javax.swing.JTextField txtUp;
    // End of variables declaration//GEN-END:variables
}
