/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.ImageIcon;
import model.info;

/**
 *
 * @author snehaswaroop
 */
public class FinalReport extends javax.swing.JPanel {

    /**
     * Creates new form FinalReport
     */
    
    info Info;
    
    public FinalReport(info Info) {
        initComponents();
        this.Info = Info;
        
        displayReport();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblReportFirstName = new javax.swing.JLabel();
        lblReportLastName = new javax.swing.JLabel();
        lblReportPhNum = new javax.swing.JLabel();
        lblReportDOB = new javax.swing.JLabel();
        lblReportAge = new javax.swing.JLabel();
        lblReportHeight = new javax.swing.JLabel();
        lblPersonalInfo = new javax.swing.JLabel();
        txtReportFirstName = new javax.swing.JTextField();
        txtReportLastName = new javax.swing.JTextField();
        txtReportPhNum = new javax.swing.JTextField();
        txtReportDOB = new javax.swing.JTextField();
        txtReportAge = new javax.swing.JTextField();
        txtReportHeight = new javax.swing.JTextField();
        lblReportWeight = new javax.swing.JLabel();
        txtReportWeight = new javax.swing.JTextField();
        lblReportSSN = new javax.swing.JLabel();
        txtReportSSN = new javax.swing.JTextField();
        lblReportStreetAdd = new javax.swing.JLabel();
        lblReportCity = new javax.swing.JLabel();
        lblReportState = new javax.swing.JLabel();
        txtReportStreetAddress = new javax.swing.JTextField();
        txtReportCity = new javax.swing.JTextField();
        txtReportZipCode = new javax.swing.JTextField();
        lblReportZipCode = new javax.swing.JLabel();
        txtReportState = new javax.swing.JTextField();
        lblReportBankInfo = new javax.swing.JLabel();
        lblReportBankName = new javax.swing.JLabel();
        lblReportRoutingNum = new javax.swing.JLabel();
        txtReportBankName = new javax.swing.JTextField();
        txtReportRoutingNum = new javax.swing.JTextField();
        lblReportAccNum = new javax.swing.JLabel();
        txtReportAccountNum = new javax.swing.JTextField();
        lblReportSavingBal = new javax.swing.JLabel();
        txtReportSavingBal = new javax.swing.JTextField();
        lblReportCheckingBal = new javax.swing.JLabel();
        txtReportCheckingBal = new javax.swing.JTextField();
        lblReportRecordNum = new javax.swing.JLabel();
        lblReportAllergy1 = new javax.swing.JLabel();
        lblReportAllergy2 = new javax.swing.JLabel();
        lblReportAllergy3 = new javax.swing.JLabel();
        txtReportRecordNum = new javax.swing.JTextField();
        lblReportLicInfo = new javax.swing.JLabel();
        lblLicenseNum = new javax.swing.JLabel();
        lblReportDOI = new javax.swing.JLabel();
        lblReportDOE = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        txtReportAllergy1 = new javax.swing.JTextField();
        txtReportAllergy2 = new javax.swing.JTextField();
        txtReportAllergy3 = new javax.swing.JTextField();
        txtReportLicenseNum = new javax.swing.JTextField();
        txtReportDOI = new javax.swing.JTextField();
        txtReportDOE = new javax.swing.JTextField();
        lblReportBloodType = new javax.swing.JLabel();
        txtReportBloodType = new javax.swing.JTextField();
        lblimg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Final Report");

        lblReportFirstName.setText("First Name");

        lblReportLastName.setText("Last Name");

        lblReportPhNum.setText("Phone Number");

        lblReportDOB.setText("Date Of Birth");

        lblReportAge.setText("Age");

        lblReportHeight.setText("Height");

        lblPersonalInfo.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lblPersonalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonalInfo.setText("Personal and Address Information");

        txtReportFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReportFirstNameActionPerformed(evt);
            }
        });

        lblReportWeight.setText("Weight");

        lblReportSSN.setText("SSN");

        lblReportStreetAdd.setText("Street Address");

        lblReportCity.setText("City");

        lblReportState.setText("State");

        txtReportStreetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReportStreetAddressActionPerformed(evt);
            }
        });

        lblReportZipCode.setText("Zip Code");

        lblReportBankInfo.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lblReportBankInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportBankInfo.setText("Bank and Medical Information");

        lblReportBankName.setText("Bank Name");

        lblReportRoutingNum.setText("Routing Number");

        txtReportRoutingNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReportRoutingNumActionPerformed(evt);
            }
        });

        lblReportAccNum.setText("Account Number");

        lblReportSavingBal.setText("Saving Balance");

        lblReportCheckingBal.setText("Checking Balance");

        txtReportCheckingBal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReportCheckingBalActionPerformed(evt);
            }
        });

        lblReportRecordNum.setText("Medical Number");

        lblReportAllergy1.setText("Allergy 1");

        lblReportAllergy2.setText("Allergy 2");

        lblReportAllergy3.setText("Allergy 3");

        txtReportRecordNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReportRecordNumActionPerformed(evt);
            }
        });

        lblReportLicInfo.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lblReportLicInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportLicInfo.setText("License Information");

        lblLicenseNum.setText("License Number");

        lblReportDOI.setText("Date Of Issue");

        lblReportDOE.setText("Date Of Expiration");

        lblPicture.setText("Picture");

        txtReportAllergy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReportAllergy2ActionPerformed(evt);
            }
        });

        txtReportDOE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReportDOEActionPerformed(evt);
            }
        });

        lblReportBloodType.setText("Blood Type");

        lblimg.setBackground(new java.awt.Color(0, 0, 0));
        lblimg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblReportSSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblReportWeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblReportHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblReportAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblReportDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblReportPhNum, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(lblReportLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblReportFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtReportFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(txtReportLastName)
                                    .addComponent(txtReportPhNum)
                                    .addComponent(txtReportDOB)
                                    .addComponent(txtReportAge)
                                    .addComponent(txtReportHeight)
                                    .addComponent(txtReportWeight)
                                    .addComponent(txtReportSSN)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReportStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReportStreetAddress))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReportCity, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReportCity))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReportState, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReportState, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReportZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReportZipCode)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReportBankInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblReportBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblReportRoutingNum, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblReportAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblReportSavingBal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(102, 102, 102)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtReportRoutingNum, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtReportBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtReportAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtReportSavingBal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblReportRecordNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblReportCheckingBal, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                            .addComponent(lblReportAllergy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblReportAllergy3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblReportAllergy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(102, 102, 102)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtReportAllergy1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(txtReportRecordNum)
                                            .addComponent(txtReportCheckingBal)
                                            .addComponent(txtReportAllergy2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtReportAllergy3))))
                                .addGap(0, 83, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblReportDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReportDOE, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReportBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtReportDOI)
                                    .addComponent(txtReportDOE)
                                    .addComponent(lblimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtReportLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReportBloodType)))
                            .addComponent(lblReportLicInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(44, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblReportBankInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblReportLicInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblReportFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReportFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReportBankName)
                                    .addComponent(txtReportBankName))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblReportLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtReportLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblReportRoutingNum)
                                        .addComponent(txtReportRoutingNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtReportPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReportPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReportAccNum)
                                    .addComponent(txtReportAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblReportDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReportDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReportSavingBal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReportSavingBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblReportCheckingBal)
                                    .addComponent(lblReportAge, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReportAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReportCheckingBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblReportHeight)
                                    .addComponent(txtReportHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblReportRecordNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtReportRecordNum))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblReportWeight)
                                    .addComponent(txtReportWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblReportAllergy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtReportAllergy1))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblReportAllergy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtReportAllergy2)
                                    .addComponent(lblReportSSN)
                                    .addComponent(txtReportSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(lblReportAllergy3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(txtReportAllergy3))
                                        .addGap(20, 20, 20))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblReportStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtReportStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLicenseNum)
                                        .addGap(29, 29, 29)
                                        .addComponent(lblReportDOI)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(130, 130, 130)
                                                .addComponent(lblPicture))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(lblReportDOE, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblReportBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtReportLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(txtReportDOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtReportDOE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtReportBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblReportCity, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReportCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReportState)
                    .addComponent(txtReportState, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReportZipCode)
                    .addComponent(txtReportZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtReportFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportFirstNameActionPerformed

    private void txtReportRoutingNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportRoutingNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportRoutingNumActionPerformed

    private void txtReportCheckingBalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportCheckingBalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportCheckingBalActionPerformed

    private void txtReportRecordNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportRecordNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportRecordNumActionPerformed

    private void txtReportStreetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportStreetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportStreetAddressActionPerformed

    private void txtReportAllergy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportAllergy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportAllergy2ActionPerformed

    private void txtReportDOEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportDOEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportDOEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JLabel lblPersonalInfo;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblReportAccNum;
    private javax.swing.JLabel lblReportAge;
    private javax.swing.JLabel lblReportAllergy1;
    private javax.swing.JLabel lblReportAllergy2;
    private javax.swing.JLabel lblReportAllergy3;
    private javax.swing.JLabel lblReportBankInfo;
    private javax.swing.JLabel lblReportBankName;
    private javax.swing.JLabel lblReportBloodType;
    private javax.swing.JLabel lblReportCheckingBal;
    private javax.swing.JLabel lblReportCity;
    private javax.swing.JLabel lblReportDOB;
    private javax.swing.JLabel lblReportDOE;
    private javax.swing.JLabel lblReportDOI;
    private javax.swing.JLabel lblReportFirstName;
    private javax.swing.JLabel lblReportHeight;
    private javax.swing.JLabel lblReportLastName;
    private javax.swing.JLabel lblReportLicInfo;
    private javax.swing.JLabel lblReportPhNum;
    private javax.swing.JLabel lblReportRecordNum;
    private javax.swing.JLabel lblReportRoutingNum;
    private javax.swing.JLabel lblReportSSN;
    private javax.swing.JLabel lblReportSavingBal;
    private javax.swing.JLabel lblReportState;
    private javax.swing.JLabel lblReportStreetAdd;
    private javax.swing.JLabel lblReportWeight;
    private javax.swing.JLabel lblReportZipCode;
    private javax.swing.JLabel lblimg;
    private javax.swing.JTextField txtReportAccountNum;
    private javax.swing.JTextField txtReportAge;
    private javax.swing.JTextField txtReportAllergy1;
    private javax.swing.JTextField txtReportAllergy2;
    private javax.swing.JTextField txtReportAllergy3;
    private javax.swing.JTextField txtReportBankName;
    private javax.swing.JTextField txtReportBloodType;
    private javax.swing.JTextField txtReportCheckingBal;
    private javax.swing.JTextField txtReportCity;
    private javax.swing.JTextField txtReportDOB;
    private javax.swing.JTextField txtReportDOE;
    private javax.swing.JTextField txtReportDOI;
    private javax.swing.JTextField txtReportFirstName;
    private javax.swing.JTextField txtReportHeight;
    private javax.swing.JTextField txtReportLastName;
    private javax.swing.JTextField txtReportLicenseNum;
    private javax.swing.JTextField txtReportPhNum;
    private javax.swing.JTextField txtReportRecordNum;
    private javax.swing.JTextField txtReportRoutingNum;
    private javax.swing.JTextField txtReportSSN;
    private javax.swing.JTextField txtReportSavingBal;
    private javax.swing.JTextField txtReportState;
    private javax.swing.JTextField txtReportStreetAddress;
    private javax.swing.JTextField txtReportWeight;
    private javax.swing.JTextField txtReportZipCode;
    // End of variables declaration//GEN-END:variables

    private void displayReport() {
        
       
        
        
        txtReportFirstName.setText(Info.getFirstName());
        txtReportLastName.setText(Info.getLastName());
        txtReportPhNum.setText(Info.getPhoneNumber());
        txtReportDOB.setText(Info.getDate_Of_Birth());
        txtReportAge.setText(Info.getAge());
        txtReportHeight.setText(Info.getHeight());
        txtReportWeight.setText(Info.getWeight());
        txtReportSSN.setText(Info.getSSN());
        //txtReportAddress.setText(Info.getStreet_Address() + " " + Info.getCity() + "" + Info.getState()+ "" + Info.getZip_Code());
        
        txtReportStreetAddress.setText(Info.getStreet_Address());
        txtReportCity.setText(Info.getCity());
        txtReportZipCode.setText(Info.getState());
        txtReportState.setText(Info.getZip_Code());
        
        
        txtReportBankName.setText(Info.getBank_Name());
        txtReportRoutingNum.setText(Info.getRouting_Number());
        txtReportAccountNum.setText(Info.getAccount_Number());
        txtReportSavingBal.setText(Info.getAccount_Bal_Saving());
        txtReportCheckingBal.setText(Info.getAccount_Bal_Checking());
        
        txtReportLicenseNum.setText(Info.getLicense_Number());
        txtReportDOI.setText(Info.getDate_Of_Issue());
        txtReportDOE.setText(Info.getDate_Of_Expiration());
        txtReportBloodType.setText(Info.getBlood_Type());
        
        
        txtReportRecordNum.setText(Info.getMedical_record_Number());
        txtReportAllergy1.setText(Info.getAllergy1());
        txtReportAllergy2.setText(Info.getAllergy2());
        txtReportAllergy3.setText(Info.getAllergy3());
        
        //String Path = Info.getPic();
        //ImageIcon pic = new ImageIcon(Path);
        //lblimg.setIcon(pic);
        
        
        
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
