/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.info;

/**
 *
 * @author snehaswaroop
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    info Info;
    
    public MainJFrame() {
        initComponents();
        
        Info = new info();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        LeftPane = new javax.swing.JPanel();
        btnCreateInfo = new javax.swing.JButton();
        btnViewInfo = new javax.swing.JButton();
        btnCreateAdd = new javax.swing.JButton();
        btnViewAdd = new javax.swing.JButton();
        btnCreateBank = new javax.swing.JButton();
        btnViewBank = new javax.swing.JButton();
        btnCreateLicense = new javax.swing.JButton();
        btnViewLicense = new javax.swing.JButton();
        btnCreateMed = new javax.swing.JButton();
        btnViewMed = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnCreateChecking = new javax.swing.JButton();
        btnViewChecking = new javax.swing.JButton();
        RightPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        LeftPane.setBackground(new java.awt.Color(255, 255, 204));
        LeftPane.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        LeftPane.setToolTipText("");

        btnCreateInfo.setFont(new java.awt.Font("Avenir", 1, 13)); // NOI18N
        btnCreateInfo.setText("Create Personal Info");
        btnCreateInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCreateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateInfoActionPerformed(evt);
            }
        });

        btnViewInfo.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        btnViewInfo.setText("View Personal Info");
        btnViewInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInfoActionPerformed(evt);
            }
        });

        btnCreateAdd.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        btnCreateAdd.setText("Create Address Info");
        btnCreateAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAddActionPerformed(evt);
            }
        });

        btnViewAdd.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        btnViewAdd.setText("View Address Info");
        btnViewAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAddActionPerformed(evt);
            }
        });

        btnCreateBank.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        btnCreateBank.setText("Create Savings Bank Details");
        btnCreateBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBankActionPerformed(evt);
            }
        });

        btnViewBank.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        btnViewBank.setText("View Savings Bank Details");
        btnViewBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBankActionPerformed(evt);
            }
        });

        btnCreateLicense.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        btnCreateLicense.setText("Create License Info");
        btnCreateLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateLicenseActionPerformed(evt);
            }
        });

        btnViewLicense.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        btnViewLicense.setText("View License Info");
        btnViewLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLicenseActionPerformed(evt);
            }
        });

        btnCreateMed.setFont(new java.awt.Font("Avenir", 1, 13)); // NOI18N
        btnCreateMed.setText("Create Medical Record");
        btnCreateMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMedActionPerformed(evt);
            }
        });

        btnViewMed.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        btnViewMed.setText("View Medical Record");
        btnViewMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedActionPerformed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        btnReport.setText("Generate Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnCreateChecking.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        btnCreateChecking.setText("Create Checking Bank Details");
        btnCreateChecking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCheckingActionPerformed(evt);
            }
        });

        btnViewChecking.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        btnViewChecking.setText("View Checking Bank Details");
        btnViewChecking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCheckingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftPaneLayout = new javax.swing.GroupLayout(LeftPane);
        LeftPane.setLayout(LeftPaneLayout);
        LeftPaneLayout.setHorizontalGroup(
            LeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPaneLayout.createSequentialGroup()
                .addGroup(LeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateLicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewLicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateChecking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewChecking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LeftPaneLayout.setVerticalGroup(
            LeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPaneLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(btnCreateInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateBank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewBank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateChecking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewChecking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateLicense)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewLicense)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateMed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewMed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReport)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(LeftPane);

        RightPane.setBackground(new java.awt.Color(255, 255, 204));
        RightPane.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));

        javax.swing.GroupLayout RightPaneLayout = new javax.swing.GroupLayout(RightPane);
        RightPane.setLayout(RightPaneLayout);
        RightPaneLayout.setHorizontalGroup(
            RightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        RightPaneLayout.setVerticalGroup(
            RightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(RightPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateInfoActionPerformed
        // TODO add your handling code here:
        
        CreateInfo createinfo = new CreateInfo(Info);
        SplitPane.setRightComponent(createinfo);
        
    }//GEN-LAST:event_btnCreateInfoActionPerformed

    private void btnViewMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedActionPerformed
        // TODO add your handling code here:
        
        ViewMedical viewmedical = new ViewMedical(Info);
        SplitPane.setRightComponent(viewmedical);
        
    }//GEN-LAST:event_btnViewMedActionPerformed

    private void btnViewAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAddActionPerformed
        // TODO add your handling code here:
        ViewAdd viewadd = new ViewAdd(Info);
        SplitPane.setRightComponent(viewadd);
        
    }//GEN-LAST:event_btnViewAddActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        
        FinalReport finalreport = new FinalReport(Info);
        SplitPane.setRightComponent(finalreport);
        
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnViewInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInfoActionPerformed
        // TODO add your handling code here:
        
        ViewInfo viewinfo = new ViewInfo(Info);
        SplitPane.setRightComponent(viewinfo);
    }//GEN-LAST:event_btnViewInfoActionPerformed

    private void btnCreateAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAddActionPerformed
        // TODO add your handling code here:
        
        CreateAdd createadd = new CreateAdd(Info);
        SplitPane.setRightComponent(createadd);
        
    }//GEN-LAST:event_btnCreateAddActionPerformed

    private void btnCreateLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateLicenseActionPerformed
        // TODO add your handling code here:
        
        CreateLicense createlic = new CreateLicense(Info);
        SplitPane.setRightComponent(createlic);
        
    }//GEN-LAST:event_btnCreateLicenseActionPerformed

    private void btnViewLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLicenseActionPerformed
        // TODO add your handling code here:
        
        ViewLic viewlic = new ViewLic(Info);
        SplitPane.setRightComponent(viewlic);
        
    }//GEN-LAST:event_btnViewLicenseActionPerformed

    private void btnCreateMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMedActionPerformed
        // TODO add your handling code here:
        
        CreateMedical createmedical = new CreateMedical(Info);
        SplitPane.setRightComponent(createmedical);
        
    }//GEN-LAST:event_btnCreateMedActionPerformed

    private void btnCreateBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBankActionPerformed
        // TODO add your handling code here:
        
        CreateSaving createsaving = new CreateSaving(Info);
        SplitPane.setRightComponent(createsaving);
        
    }//GEN-LAST:event_btnCreateBankActionPerformed

    private void btnViewBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBankActionPerformed
        // TODO add your handling code here:
        
        ViewSaving viewsaving = new ViewSaving(Info);
        SplitPane.setRightComponent(viewsaving);
    }//GEN-LAST:event_btnViewBankActionPerformed

    private void btnCreateCheckingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCheckingActionPerformed
        // TODO add your handling code here:
        
        CreateChecking createchecking = new CreateChecking(Info);
        SplitPane.setRightComponent(createchecking);
        
    }//GEN-LAST:event_btnCreateCheckingActionPerformed

    private void btnViewCheckingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCheckingActionPerformed
        // TODO add your handling code here:
        
        ViewChecking viewchecking = new ViewChecking(Info);
        SplitPane.setRightComponent(viewchecking);
    }//GEN-LAST:event_btnViewCheckingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftPane;
    private javax.swing.JPanel RightPane;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnCreateAdd;
    private javax.swing.JButton btnCreateBank;
    private javax.swing.JButton btnCreateChecking;
    private javax.swing.JButton btnCreateInfo;
    private javax.swing.JButton btnCreateLicense;
    private javax.swing.JButton btnCreateMed;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnViewAdd;
    private javax.swing.JButton btnViewBank;
    private javax.swing.JButton btnViewChecking;
    private javax.swing.JButton btnViewInfo;
    private javax.swing.JButton btnViewLicense;
    private javax.swing.JButton btnViewMed;
    // End of variables declaration//GEN-END:variables
}
