/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.info;

/**
 *
 * @author snehaswaroop
 */
public class ViewChecking extends javax.swing.JPanel {

    /**
     * Creates new form ViewChecking
     */
    
    info Info;
    
    public ViewChecking(info Info) {
        initComponents();
        this.Info = Info;
        
        displaychecking();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblViewCheckingBank = new javax.swing.JLabel();
        lblViewBankName = new javax.swing.JLabel();
        lblViewRoutingNum = new javax.swing.JLabel();
        lblViewAccountNum = new javax.swing.JLabel();
        lblViewSavingInfo = new javax.swing.JLabel();
        lblViewcheckingBalance = new javax.swing.JLabel();
        txtViewBankName = new javax.swing.JTextField();
        txtViewRoutingNum = new javax.swing.JTextField();
        txtViewAccountNum = new javax.swing.JTextField();
        txtViewCheckingAccBal = new javax.swing.JTextField();

        setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        lblViewCheckingBank.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblViewCheckingBank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewCheckingBank.setText("View Bank Information");

        lblViewBankName.setText("Bank Name");

        lblViewRoutingNum.setText("Bank Routing Number");

        lblViewAccountNum.setText("Account Number");

        lblViewSavingInfo.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        lblViewSavingInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewSavingInfo.setText("View Checking Account Information");

        lblViewcheckingBalance.setText("Account Balance");

        txtViewBankName.setEditable(false);

        txtViewRoutingNum.setEditable(false);
        txtViewRoutingNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewRoutingNumActionPerformed(evt);
            }
        });

        txtViewAccountNum.setEditable(false);

        txtViewCheckingAccBal.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblViewCheckingBank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblViewRoutingNum)
                            .addComponent(lblViewAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblViewBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtViewBankName)
                            .addComponent(txtViewRoutingNum)
                            .addComponent(txtViewAccountNum, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(127, Short.MAX_VALUE)
                        .addComponent(lblViewcheckingBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(txtViewCheckingAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewSavingInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblViewCheckingBank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewBankName)
                    .addComponent(txtViewBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewRoutingNum)
                    .addComponent(txtViewRoutingNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewAccountNum)
                    .addComponent(txtViewAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblViewSavingInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewcheckingBalance)
                    .addComponent(txtViewCheckingAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtViewRoutingNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewRoutingNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewRoutingNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblViewAccountNum;
    private javax.swing.JLabel lblViewBankName;
    private javax.swing.JLabel lblViewCheckingBank;
    private javax.swing.JLabel lblViewRoutingNum;
    private javax.swing.JLabel lblViewSavingInfo;
    private javax.swing.JLabel lblViewcheckingBalance;
    private javax.swing.JTextField txtViewAccountNum;
    private javax.swing.JTextField txtViewBankName;
    private javax.swing.JTextField txtViewCheckingAccBal;
    private javax.swing.JTextField txtViewRoutingNum;
    // End of variables declaration//GEN-END:variables

    private void displaychecking() {
        
        txtViewBankName.setText(Info.getBank_Name());
        txtViewRoutingNum.setText(Info.getRouting_Number());
        txtViewAccountNum.setText(Info.getAccount_Number());
        txtViewCheckingAccBal.setText(Info.getAccount_Bal_Checking());
        
        
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
