/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.info;

/**
 *
 * @author snehaswaroop
 */



public class ViewMedical extends javax.swing.JPanel {

    /**
     * Creates new form ViewMedical
     */
    info Info;
    
    public ViewMedical(info Info) {
        initComponents();
        this.Info = Info;
        
        displaymed();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblViewMedicalInfo = new javax.swing.JLabel();
        lblViewMedicalNum = new javax.swing.JLabel();
        lblViewAllergy1 = new javax.swing.JLabel();
        lblViewAllergy2 = new javax.swing.JLabel();
        lblViewAllergy3 = new javax.swing.JLabel();
        txtViewMedicalNum = new javax.swing.JTextField();
        txtViewAllergy1 = new javax.swing.JTextField();
        txtViewAllergy2 = new javax.swing.JTextField();
        txtViewAllergy3 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        lblViewMedicalInfo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblViewMedicalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewMedicalInfo.setText("View Medical Record");

        lblViewMedicalNum.setText("Medical Number");

        lblViewAllergy1.setText("Allergy 1");

        lblViewAllergy2.setText("Allergy 2");

        lblViewAllergy3.setText("Allergy 3");

        txtViewMedicalNum.setEditable(false);

        txtViewAllergy1.setEditable(false);

        txtViewAllergy2.setEditable(false);
        txtViewAllergy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewAllergy2ActionPerformed(evt);
            }
        });

        txtViewAllergy3.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblViewMedicalInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewMedicalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewAllergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewAllergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewAllergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtViewMedicalNum)
                    .addComponent(txtViewAllergy1)
                    .addComponent(txtViewAllergy2)
                    .addComponent(txtViewAllergy3, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lblViewMedicalInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblViewMedicalNum)
                            .addComponent(txtViewMedicalNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(lblViewAllergy1))
                    .addComponent(txtViewAllergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewAllergy2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtViewAllergy2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewAllergy3)
                    .addComponent(txtViewAllergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtViewAllergy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewAllergy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewAllergy2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblViewAllergy1;
    private javax.swing.JLabel lblViewAllergy2;
    private javax.swing.JLabel lblViewAllergy3;
    private javax.swing.JLabel lblViewMedicalInfo;
    private javax.swing.JLabel lblViewMedicalNum;
    private javax.swing.JTextField txtViewAllergy1;
    private javax.swing.JTextField txtViewAllergy2;
    private javax.swing.JTextField txtViewAllergy3;
    private javax.swing.JTextField txtViewMedicalNum;
    // End of variables declaration//GEN-END:variables

    private void displaymed() {
        
        txtViewMedicalNum.setText(Info.getMedical_record_Number());
        txtViewAllergy1.setText(Info.getAllergy1());
        txtViewAllergy2.setText(Info.getAllergy2());
        txtViewAllergy3.setText(Info.getAllergy3());
        
        
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
