/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.info;

/**
 *
 * @author snehaswaroop
 */
public class ViewInfo extends javax.swing.JPanel {

    /**
     * Creates new form ViewInfo
     */
    
    info Info;
    
    public ViewInfo(info Info) {
        initComponents();
        
        this.Info = Info;
        
        displayInfo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewInfo = new javax.swing.JLabel();
        lblViewFirstName = new javax.swing.JLabel();
        lblViewLastName = new javax.swing.JLabel();
        lblViewPhNo = new javax.swing.JLabel();
        lblViewDOB = new javax.swing.JLabel();
        lblViewAge = new javax.swing.JLabel();
        lblViewHeight = new javax.swing.JLabel();
        lblViewWeight = new javax.swing.JLabel();
        lblViewSSN = new javax.swing.JLabel();
        txtViewFirstName = new javax.swing.JTextField();
        txtViewLastName = new javax.swing.JTextField();
        txtViewPhNo = new javax.swing.JTextField();
        txtViewAge = new javax.swing.JTextField();
        txtViewDOB = new javax.swing.JTextField();
        txtViewHeight = new javax.swing.JTextField();
        txtViewWeight = new javax.swing.JTextField();
        txtViewSSN = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));

        lblViewInfo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblViewInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewInfo.setText("View Personal Information");

        lblViewFirstName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFirstName.setText("First Name");

        lblViewLastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewLastName.setText("Last Name");

        lblViewPhNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewPhNo.setText("Phone Number");

        lblViewDOB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewDOB.setText("Date Of Birth");

        lblViewAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewAge.setText("Age");

        lblViewHeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewHeight.setText("Height");

        lblViewWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewWeight.setText("Weight");

        lblViewSSN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewSSN.setText("SSN");

        txtViewFirstName.setEditable(false);

        txtViewLastName.setEditable(false);

        txtViewPhNo.setEditable(false);

        txtViewAge.setEditable(false);

        txtViewDOB.setEditable(false);

        txtViewHeight.setEditable(false);

        txtViewWeight.setEditable(false);

        txtViewSSN.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblViewSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(txtViewSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblViewWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtViewWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblViewHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtViewHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblViewAge, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtViewAge, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblViewDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtViewDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblViewPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtViewPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblViewLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblViewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtViewFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(txtViewLastName))))
                .addContainerGap(110, Short.MAX_VALUE))
            .addComponent(lblViewInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lblViewInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtViewFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewLastName)
                    .addComponent(txtViewLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewPhNo)
                    .addComponent(txtViewPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewDOB)
                    .addComponent(txtViewDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewAge)
                    .addComponent(txtViewAge, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewHeight)
                    .addComponent(txtViewHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewWeight)
                    .addComponent(txtViewWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewSSN)
                    .addComponent(txtViewSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblViewAge;
    private javax.swing.JLabel lblViewDOB;
    private javax.swing.JLabel lblViewFirstName;
    private javax.swing.JLabel lblViewHeight;
    private javax.swing.JLabel lblViewInfo;
    private javax.swing.JLabel lblViewLastName;
    private javax.swing.JLabel lblViewPhNo;
    private javax.swing.JLabel lblViewSSN;
    private javax.swing.JLabel lblViewWeight;
    private javax.swing.JTextField txtViewAge;
    private javax.swing.JTextField txtViewDOB;
    private javax.swing.JTextField txtViewFirstName;
    private javax.swing.JTextField txtViewHeight;
    private javax.swing.JTextField txtViewLastName;
    private javax.swing.JTextField txtViewPhNo;
    private javax.swing.JTextField txtViewSSN;
    private javax.swing.JTextField txtViewWeight;
    // End of variables declaration//GEN-END:variables

    private void displayInfo() {
        
        txtViewFirstName.setText(Info.getFirstName());
        txtViewLastName.setText(Info.getLastName());
        txtViewPhNo.setText(Info.getPhoneNumber());
        txtViewDOB.setText(Info.getDate_Of_Birth());
        txtViewAge.setText(Info.getAge());
        txtViewHeight.setText(Info.getHeight());
        txtViewWeight.setText(Info.getWeight());
        txtViewSSN.setText(Info.getSSN());
        
        
        
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
