/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Customer.Customer;

/**
 *
 * @author snehaswaroop
 */
public class ManageResturantFirstPage extends javax.swing.JPanel {
    JPanel userProcessContainer;
    EcoSystem ecosystem;

    public ManageResturantFirstPage(JPanel userprocesscontainer, EcoSystem ecosystem) {
        this.userProcessContainer = userprocesscontainer;
        this.ecosystem = ecosystem;
        initComponents();
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblRestaurant.getModel();
        model.setRowCount(0);
        if (ecosystem.getRestaurantDirectory().getRestaurantList() != null) {
            for(Restaurant restaurant : ecosystem.getRestaurantDirectory().getRestaurantList()) {
                Object row[] = new Object[2];
                row[0] = restaurant;
                row[1] = restaurant.getRestaurantAddress();
                model.addRow(row); 
            }       
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageRestaurant = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurant = new javax.swing.JTable();
        btnAddRestaurant = new javax.swing.JButton();
        btnModifyRestaurant = new javax.swing.JButton();
        btnDeleteRestaurant = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        lblManageRestaurant.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        lblManageRestaurant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageRestaurant.setText("Manage Restaurants");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblRestaurant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Restaurant Name", "Restaurant Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRestaurant);

        btnAddRestaurant.setText("Add Restaurant");
        btnAddRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRestaurantActionPerformed(evt);
            }
        });

        btnModifyRestaurant.setText("Modify Restaurant");
        btnModifyRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyRestaurantActionPerformed(evt);
            }
        });

        btnDeleteRestaurant.setText("Delete Restaurant");
        btnDeleteRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRestaurantActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblManageRestaurant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(btnAddRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnModifyRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnDeleteRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblManageRestaurant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRestaurant)
                    .addComponent(btnModifyRestaurant)
                    .addComponent(btnDeleteRestaurant))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        Component[] component = userProcessContainer.getComponents();
          for (Component comp : component){
            if (comp instanceof SystemAdminWorkAreaJPanel){
                System.out.println(comp);
                SystemAdminWorkAreaJPanel panel = (SystemAdminWorkAreaJPanel) comp;
                panel.populateTree();
            }
        }
        cardlayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRestaurantActionPerformed
        // TODO add your handling code here:
        AddNewResturantPanel panel = new AddNewResturantPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("AddRestaurant", panel);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_btnAddRestaurantActionPerformed

    private void btnModifyRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyRestaurantActionPerformed
        int selectedRowIndex = tblRestaurant.getSelectedRow();
        if (selectedRowIndex<0) {
            JOptionPane.showMessageDialog(null,"Please select a restaurant to modify", "Warning", JOptionPane.WARNING_MESSAGE); 
        }
        else {
            Restaurant selectedRestaurant = (Restaurant) tblRestaurant.getValueAt(selectedRowIndex, 0);
            ModifyRestaurantPanel panel = new ModifyRestaurantPanel(userProcessContainer, selectedRestaurant);
            userProcessContainer.add("ModifyRestaurant", panel);
            CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            populateTable();
        }
    }//GEN-LAST:event_btnModifyRestaurantActionPerformed

    private void btnDeleteRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRestaurantActionPerformed
        int selectedRowIndex = tblRestaurant.getSelectedRow();
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(null,"Please select a restaurant to delete", "Warning", JOptionPane.WARNING_MESSAGE); 
        }
        else {
            Restaurant restaurant = (Restaurant) tblRestaurant.getValueAt(selectedRowIndex, 0);
            this.ecosystem.getUserAccountDirectory().deleteUser(restaurant.getAdmin().getUsername());           //Delete the UserAccount
            this.ecosystem.getRestaurantDirectory().getRestaurantList().remove(restaurant);                     //Delete the Restaurant from the ecosystem
            JOptionPane.showMessageDialog(null, "Deleted the selected Restaurant successfully");
            populateTable();
        }
            
    }//GEN-LAST:event_btnDeleteRestaurantActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRestaurant;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteRestaurant;
    private javax.swing.JButton btnModifyRestaurant;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageRestaurant;
    private javax.swing.JTable tblRestaurant;
    // End of variables declaration//GEN-END:variables
}
